/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module adder (
  input A,
  input B,
  input C_in,
  output SUM,
  output CARRY
);
  wire s0;
  assign s0 = (A ^ B);
  assign CARRY = ((A & B) | (s0 & C_in));
  assign SUM = (s0 ^ C_in);
endmodule

module \8_BIT_ADDER  (
  input [7:0] A,
  input [7:0] B,
  input CARRY_IN,
  output [7:0] SUM,
  output CARRY_OUT
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  assign s0 = A[0];
  assign s4 = A[1];
  assign s8 = A[2];
  assign s12 = A[3];
  assign s16 = A[4];
  assign s20 = A[5];
  assign s24 = A[6];
  assign s28 = A[7];
  assign s1 = B[0];
  assign s5 = B[1];
  assign s9 = B[2];
  assign s13 = B[3];
  assign s17 = B[4];
  assign s21 = B[5];
  assign s25 = B[6];
  assign s29 = B[7];
  adder adder_i0 (
    .A( s0 ),
    .B( s1 ),
    .C_in( CARRY_IN ),
    .SUM( s2 ),
    .CARRY( s3 )
  );
  adder adder_i1 (
    .A( s4 ),
    .B( s5 ),
    .C_in( s3 ),
    .SUM( s6 ),
    .CARRY( s7 )
  );
  adder adder_i2 (
    .A( s8 ),
    .B( s9 ),
    .C_in( s7 ),
    .SUM( s10 ),
    .CARRY( s11 )
  );
  adder adder_i3 (
    .A( s12 ),
    .B( s13 ),
    .C_in( s11 ),
    .SUM( s14 ),
    .CARRY( s15 )
  );
  adder adder_i4 (
    .A( s16 ),
    .B( s17 ),
    .C_in( s15 ),
    .SUM( s18 ),
    .CARRY( s19 )
  );
  adder adder_i5 (
    .A( s20 ),
    .B( s21 ),
    .C_in( s19 ),
    .SUM( s22 ),
    .CARRY( s23 )
  );
  adder adder_i6 (
    .A( s24 ),
    .B( s25 ),
    .C_in( s23 ),
    .SUM( s26 ),
    .CARRY( s27 )
  );
  adder adder_i7 (
    .A( s28 ),
    .B( s29 ),
    .C_in( s27 ),
    .SUM( s30 ),
    .CARRY( CARRY_OUT )
  );
  assign SUM[0] = s2;
  assign SUM[1] = s6;
  assign SUM[2] = s10;
  assign SUM[3] = s14;
  assign SUM[4] = s18;
  assign SUM[5] = s22;
  assign SUM[6] = s26;
  assign SUM[7] = s30;
endmodule

module FULL_ADDSUB (
  input [7:0] B,
  input [7:0] A,
  input MODE,
  output [7:0] OUT
);
  wire [7:0] s0;
  wire s1;
  wire [8:0] s2;
  Mux_2x1_NBits #(
    .Bits(9)
  )
  Mux_2x1_NBits_i0 (
    .sel( MODE ),
    .in_0( 9'b0 ),
    .in_1( 9'b111111111 ),
    .out( s2 )
  );
  assign s0 = (B ^ s2[8:1]);
  assign s1 = s2[0];
  \8_BIT_ADDER  \8_BIT_ADDER_i1 (
    .A( A ),
    .B( s0 ),
    .CARRY_IN( s1 ),
    .SUM( OUT )
  );
endmodule

module DemuxBus1
#(
    parameter Bits = 2,
    parameter Default = 0 
)
(
    output [(Bits-1):0] out_0,
    output [(Bits-1):0] out_1,
    input [0:0] sel,
    input [(Bits-1):0] in
);
    assign out_0 = (sel == 1'h0)? in : Default;
    assign out_1 = (sel == 1'h1)? in : Default;
endmodule


module SHIFTFUN (
  input [7:0] A,
  input [7:0] B,
  input SELECTION,
  input SHIFT_SELECTION,
  output [7:0] LEFTOUT,
  output [7:0] RIGHTOUT
);
  wire [7:0] s0;
  wire [7:0] s1;
  wire [7:0] s2;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i0 (
    .sel( SELECTION ),
    .in_0( A ),
    .in_1( B ),
    .out( s0 )
  );
  DemuxBus1 #(
    .Bits(8),
    .Default(0)
  )
  DemuxBus1_i1 (
    .sel( SHIFT_SELECTION ),
    .in( s0 ),
    .out_0( s1 ),
    .out_1( s2 )
  );
  assign LEFTOUT[0] = 1'b0;
  assign LEFTOUT[1] = s1[0];
  assign LEFTOUT[2] = s1[1];
  assign LEFTOUT[3] = s1[2];
  assign LEFTOUT[4] = s1[3];
  assign LEFTOUT[5] = s1[4];
  assign LEFTOUT[6] = s1[5];
  assign LEFTOUT[7] = s1[6];
  assign RIGHTOUT[0] = s2[1];
  assign RIGHTOUT[1] = s2[2];
  assign RIGHTOUT[2] = s2[3];
  assign RIGHTOUT[3] = s2[4];
  assign RIGHTOUT[4] = s2[5];
  assign RIGHTOUT[5] = s2[6];
  assign RIGHTOUT[6] = s2[7];
  assign RIGHTOUT[7] = 1'b0;
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module LOGIC_BLOCK (
  input [7:0] A,
  input [7:0] B,
  input [2:0] MODE_SELECTION,
  output [7:0] OUT
);
  wire [7:0] s0;
  wire [7:0] s1;
  wire [7:0] s2;
  wire [1:0] s3;
  wire [7:0] s4;
  wire [7:0] s5;
  wire s6;
  assign s0 = (A & B);
  assign s1 = (A | B);
  assign s2 = (A ^ B);
  assign s3 = MODE_SELECTION[1:0];
  assign s6 = MODE_SELECTION[2];
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i0 (
    .sel( s3 ),
    .in_0( s0 ),
    .in_1( s1 ),
    .in_2( s2 ),
    .in_3( A ),
    .out( s4 )
  );
  assign s5[0] = s6;
  assign s5[1] = s6;
  assign s5[2] = s6;
  assign s5[3] = s6;
  assign s5[4] = s6;
  assign s5[5] = s6;
  assign s5[6] = s6;
  assign s5[7] = s6;
  assign OUT = (s4 ^ s5);
endmodule

module ALU (
  input [7:0] A,
  input [7:0] B,
  input A2,
  input A1,
  input A0,
  input A3,
  output [7:0] \OUTPUT 
);
  wire [7:0] s0;
  wire [2:0] s1;
  wire [7:0] s2;
  wire [7:0] s3;
  wire [7:0] s4;
  wire [1:0] s5;
  wire [7:0] s6;
  FULL_ADDSUB FULL_ADDSUB_i0 (
    .B( B ),
    .A( A ),
    .MODE( A1 ),
    .OUT( s0 )
  );
  SHIFTFUN SHIFTFUN_i1 (
    .A( A ),
    .B( B ),
    .SELECTION( A1 ),
    .SHIFT_SELECTION( A0 ),
    .LEFTOUT( s3 ),
    .RIGHTOUT( s4 )
  );
  assign s5[0] = A2;
  assign s5[1] = A3;
  assign s1[0] = A0;
  assign s1[1] = A1;
  assign s1[2] = A2;
  LOGIC_BLOCK LOGIC_BLOCK_i2 (
    .A( A ),
    .B( B ),
    .MODE_SELECTION( s1 ),
    .OUT( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i3 (
    .sel( A0 ),
    .in_0( s3 ),
    .in_1( s4 ),
    .out( s6 )
  );
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i4 (
    .sel( s5 ),
    .in_0( s2 ),
    .in_1( s2 ),
    .in_2( s0 ),
    .in_3( s6 ),
    .out( \OUTPUT  )
  );
endmodule
